/**
 * Dummy data for development and testing
 * Contains mock news articles, trades, and user data
 */

// Generate unique IDs
const generateId = () => `${Date.now()}-${Math.random().toString(36).substring(2, 9)}`;

// Helper to generate random past dates
const randomPastDate = (hoursAgo) => {
  const date = new Date();
  date.setHours(date.getHours() - Math.random() * hoursAgo);
  return date.toISOString();
};

/**
 * Mock news articles (20+ articles)
 */
export const mockNews = [
  {
    id: 'news-1',
    headline: 'Bitcoin Surges Past $48,000 as ETF Inflows Continue',
    brief: 'Bitcoin prices rallied today as institutional investors poured more money into spot Bitcoin ETFs. BlackRock\'s iShares Bitcoin Trust saw its largest single-day inflow since launch, signaling growing mainstream adoption.',
    source: 'CoinDesk',
    url: 'https://coindesk.com',
    category: 'Crypto',
    publishedAt: randomPastDate(0.5), // 30 mins ago
    imageUrl: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&h=400&fit=crop',
  },
  {
    id: 'news-2',
    headline: 'NVIDIA Reports Record Revenue, AI Chip Demand Soars',
    brief: 'NVIDIA\'s quarterly earnings beat analyst expectations with revenue up 265% year-over-year. CEO Jensen Huang announced expanded production of H100 and upcoming Blackwell chips to meet unprecedented AI demand.',
    source: 'Bloomberg',
    url: 'https://bloomberg.com',
    category: 'Tech',
    publishedAt: randomPastDate(1.2),
    imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=400&fit=crop',
  },
  {
    id: 'news-3',
    headline: 'Fed Signals Potential Rate Cuts in Coming Months',
    brief: 'Federal Reserve officials indicated they are considering interest rate cuts as inflation shows signs of cooling. Markets reacted positively with stocks and bonds rallying on the news.',
    source: 'Reuters',
    url: 'https://reuters.com',
    category: 'Finance',
    publishedAt: randomPastDate(2),
    imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&h=400&fit=crop',
  },
  {
    id: 'news-4',
    headline: 'Solana Network Hits New All-Time High in Daily Transactions',
    brief: 'The Solana blockchain processed over 65 million transactions in a single day, surpassing previous records. DeFi activity and memecoin trading drove the surge in network usage.',
    source: 'The Block',
    url: 'https://theblock.co',
    category: 'Crypto',
    publishedAt: randomPastDate(3),
    imageUrl: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&h=400&fit=crop',
  },
  {
    id: 'news-5',
    headline: 'Apple Unveils Vision Pro Sales Launch in New Markets',
    brief: 'Apple announced the Vision Pro mixed reality headset will expand to 10 new countries next month. Tim Cook highlighted strong developer interest with over 1,500 apps optimized for the platform.',
    source: 'TechCrunch',
    url: 'https://techcrunch.com',
    category: 'Tech',
    publishedAt: randomPastDate(4),
    imageUrl: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=800&h=400&fit=crop',
  },
  {
    id: 'news-6',
    headline: 'Oil Prices Jump on Middle East Supply Concerns',
    brief: 'Crude oil prices surged 3% as geopolitical tensions in the Middle East raised concerns about potential supply disruptions. OPEC+ members are scheduled to meet next week to discuss production levels.',
    source: 'CNBC',
    url: 'https://cnbc.com',
    category: 'Energy',
    publishedAt: randomPastDate(2.5),
    imageUrl: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800&h=400&fit=crop',
  },
  {
    id: 'news-7',
    headline: 'Ethereum ETF Approval Expected Within Weeks',
    brief: 'Multiple sources report that SEC approval for spot Ethereum ETFs is imminent. Analysts predict significant institutional inflows similar to Bitcoin ETF launches earlier this year.',
    source: 'CryptoSlate',
    url: 'https://cryptoslate.com',
    category: 'Crypto',
    publishedAt: randomPastDate(5),
    imageUrl: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&h=400&fit=crop',
  },
  {
    id: 'news-8',
    headline: 'Tesla Announces New Gigafactory Location in Asia',
    brief: 'Elon Musk confirmed Tesla will build a new manufacturing facility to meet growing EV demand in the region. The factory is expected to produce 500,000 vehicles annually by 2026.',
    source: 'Electrek',
    url: 'https://electrek.co',
    category: 'Business',
    publishedAt: randomPastDate(6),
    imageUrl: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&h=400&fit=crop',
  },
  {
    id: 'news-9',
    headline: 'Gold Reaches New Record High Amid Economic Uncertainty',
    brief: 'Gold prices hit an all-time high of $2,150 per ounce as investors seek safe-haven assets. Central bank buying and concerns over inflation continue to drive demand for the precious metal.',
    source: 'MarketWatch',
    url: 'https://marketwatch.com',
    category: 'Finance',
    publishedAt: randomPastDate(1),
    imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&h=400&fit=crop',
  },
  {
    id: 'news-10',
    headline: 'Microsoft Copilot Integration Boosts Office 365 Subscriptions',
    brief: 'Microsoft reported a 40% increase in premium Office 365 subscriptions since launching Copilot AI features. Satya Nadella announced plans to expand AI capabilities across all Microsoft products.',
    source: 'The Verge',
    url: 'https://theverge.com',
    category: 'Tech',
    publishedAt: randomPastDate(8),
    imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=400&fit=crop',
  },
  {
    id: 'news-11',
    headline: 'Dogecoin Rallies 20% on Elon Musk Twitter Activity',
    brief: 'DOGE prices spiked after Elon Musk posted dog-related content on X (formerly Twitter). Analysts warn of high volatility as memecoin trading volume surges.',
    source: 'Decrypt',
    url: 'https://decrypt.co',
    category: 'Crypto',
    publishedAt: randomPastDate(0.8),
    imageUrl: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&h=400&fit=crop',
  },
  {
    id: 'news-12',
    headline: 'Amazon Web Services Launches New AI Training Platform',
    brief: 'AWS unveiled a comprehensive AI development platform aimed at enterprise customers. The service promises 50% cost reduction for large language model training.',
    source: 'AWS Blog',
    url: 'https://aws.amazon.com',
    category: 'Tech',
    publishedAt: randomPastDate(10),
    imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=400&fit=crop',
  },
  {
    id: 'news-13',
    headline: 'European Central Bank Holds Rates Steady',
    brief: 'The ECB kept interest rates unchanged at their latest meeting, citing persistent inflation concerns. Christine Lagarde signaled a cautious approach to monetary policy for the remainder of the year.',
    source: 'Financial Times',
    url: 'https://ft.com',
    category: 'Finance',
    publishedAt: randomPastDate(12),
    imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&h=400&fit=crop',
  },
  {
    id: 'news-14',
    headline: 'Arbitrum TVL Surpasses $10 Billion Milestone',
    brief: 'The Arbitrum Layer 2 network reached $10 billion in total value locked, cementing its position as the leading Ethereum scaling solution. New DeFi protocols continue to launch on the network.',
    source: 'DeFi Pulse',
    url: 'https://defipulse.com',
    category: 'Crypto',
    publishedAt: randomPastDate(14),
    imageUrl: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&h=400&fit=crop',
  },
  {
    id: 'news-15',
    headline: 'Meta Platforms Reports Strong Advertising Revenue Growth',
    brief: 'Meta\'s quarterly results exceeded expectations with ad revenue up 25%. Mark Zuckerberg highlighted the impact of AI-powered ad targeting and strong engagement on Instagram Reels.',
    source: 'AdWeek',
    url: 'https://adweek.com',
    category: 'Business',
    publishedAt: randomPastDate(16),
    imageUrl: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&h=400&fit=crop',
  },
  {
    id: 'news-16',
    headline: 'US Senate Passes Bipartisan Crypto Regulation Bill',
    brief: 'A landmark cryptocurrency regulation bill passed the Senate with broad bipartisan support. The legislation provides clearer guidelines for digital asset classification and exchange operations.',
    source: 'Politico',
    url: 'https://politico.com',
    category: 'Politics',
    publishedAt: randomPastDate(20),
    imageUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&h=400&fit=crop',
  },
  {
    id: 'news-17',
    headline: 'AMD Announces Next-Gen AI Accelerators to Compete with NVIDIA',
    brief: 'AMD revealed its MI400 series AI chips, claiming superior price-performance ratio compared to NVIDIA\'s offerings. Major cloud providers have already committed to large orders.',
    source: 'AnandTech',
    url: 'https://anandtech.com',
    category: 'Tech',
    publishedAt: randomPastDate(18),
    imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=400&fit=crop',
  },
  {
    id: 'news-18',
    headline: 'Japanese Yen Falls to Multi-Year Low Against Dollar',
    brief: 'USD/JPY reached 158 as the Bank of Japan maintains ultra-loose monetary policy while the Fed remains hawkish. Currency traders are watching for potential intervention.',
    source: 'Forex Live',
    url: 'https://forexlive.com',
    category: 'Finance',
    publishedAt: randomPastDate(3.5),
    imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&h=400&fit=crop',
  },
  {
    id: 'news-19',
    headline: 'Chainlink Integrates with Major Banking Consortium',
    brief: 'LINK prices rose 15% after Chainlink announced a partnership with SWIFT and several major banks for cross-border payment settlements using blockchain oracle technology.',
    source: 'CoinTelegraph',
    url: 'https://cointelegraph.com',
    category: 'Crypto',
    publishedAt: randomPastDate(7),
    imageUrl: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&h=400&fit=crop',
  },
  {
    id: 'news-20',
    headline: 'Google DeepMind Achieves Breakthrough in Protein Structure Prediction',
    brief: 'DeepMind\'s latest AlphaFold model can predict protein structures with unprecedented accuracy, potentially revolutionizing drug discovery. Pharmaceutical stocks rallied on the news.',
    source: 'Nature',
    url: 'https://nature.com',
    category: 'Tech',
    publishedAt: randomPastDate(24),
    imageUrl: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&h=400&fit=crop',
  },
  {
    id: 'news-21',
    headline: 'Coinbase Stock Surges on Strong Crypto Trading Volumes',
    brief: 'COIN shares jumped 12% as the company reported record trading volumes driven by the Bitcoin ETF rally. CEO Brian Armstrong announced plans for international expansion.',
    source: 'Barron\'s',
    url: 'https://barrons.com',
    category: 'Business',
    publishedAt: randomPastDate(9),
    imageUrl: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&h=400&fit=crop',
  },
  {
    id: 'news-22',
    headline: 'OPEC+ Agrees to Extend Production Cuts',
    brief: 'Oil-producing nations agreed to maintain current output reductions through the end of the year. Brent crude responded positively to the supply constraint measures.',
    source: 'Oil Price',
    url: 'https://oilprice.com',
    category: 'Energy',
    publishedAt: randomPastDate(28),
    imageUrl: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800&h=400&fit=crop',
  },
  {
    id: 'news-23',
    headline: 'Palantir Wins $500 Million Pentagon Contract',
    brief: 'PLTR stock gained 8% after securing a major defense contract for AI-powered analytics. Alex Karp emphasized the company\'s unique position in government technology solutions.',
    source: 'Defense News',
    url: 'https://defensenews.com',
    category: 'Business',
    publishedAt: randomPastDate(15),
    imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=400&fit=crop',
  },
  {
    id: 'news-24',
    headline: 'Pepe Coin Market Cap Exceeds $5 Billion',
    brief: 'The frog-themed memecoin has surged 300% this month, driven by social media hype and new exchange listings. Traders warn of extreme volatility and potential for rapid corrections.',
    source: 'BeInCrypto',
    url: 'https://beincrypto.com',
    category: 'Crypto',
    publishedAt: randomPastDate(4.5),
    imageUrl: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&h=400&fit=crop',
  },
  {
    id: 'news-25',
    headline: 'Intel Unveils Revolutionary Chip Manufacturing Process',
    brief: 'Intel announced its Intel 18A process node is ahead of schedule, potentially reclaiming technology leadership from TSMC. Pat Gelsinger expressed confidence in the company\'s turnaround.',
    source: 'Tom\'s Hardware',
    url: 'https://tomshardware.com',
    category: 'Tech',
    publishedAt: randomPastDate(36),
    imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=400&fit=crop',
  },
];

/**
 * Mock trades (10+ trades)
 */
export const mockActiveTrades = [
  {
    id: 'trade-active-1',
    newsId: 'news-1',
    newsHeadline: 'Bitcoin Surges Past $48,000 as ETF Inflows Continue',
    market: 'BTC/USD',
    direction: 'long',
    collateral: 5,
    leverage: 75,
    entryPrice: 47500,
    currentPrice: 48200,
    takeProfit: 100,
    stopLoss: null,
    pnl: 5.52,
    pnlPercent: 110.5,
    openedAt: randomPastDate(2),
    status: 'active',
  },
  {
    id: 'trade-active-2',
    newsId: 'news-2',
    newsHeadline: 'NVIDIA Reports Record Revenue, AI Chip Demand Soars',
    market: 'NVDA/USD',
    direction: 'long',
    collateral: 2,
    leverage: 75,
    entryPrice: 495,
    currentPrice: 512,
    takeProfit: 100,
    stopLoss: null,
    pnl: 5.15,
    pnlPercent: 257.6,
    openedAt: randomPastDate(4),
    status: 'active',
  },
  {
    id: 'trade-active-3',
    newsId: 'news-6',
    newsHeadline: 'Oil Prices Jump on Middle East Supply Concerns',
    market: 'USOILSPOT/USD',
    direction: 'long',
    collateral: 1,
    leverage: 75,
    entryPrice: 82.5,
    currentPrice: 84.2,
    takeProfit: 100,
    stopLoss: null,
    pnl: 1.54,
    pnlPercent: 154.5,
    openedAt: randomPastDate(6),
    status: 'active',
  },
];

export const mockClosedTrades = [
  {
    id: 'trade-closed-1',
    newsId: 'news-3',
    newsHeadline: 'Fed Signals Potential Rate Cuts in Coming Months',
    market: 'XAU/USD',
    direction: 'long',
    collateral: 2,
    leverage: 75,
    entryPrice: 2080,
    exitPrice: 2145,
    takeProfit: 100,
    stopLoss: null,
    pnl: 4.69,
    pnlPercent: 234.4,
    openedAt: randomPastDate(48),
    closedAt: randomPastDate(24),
    status: 'closed',
  },
  {
    id: 'trade-closed-2',
    newsId: 'news-4',
    newsHeadline: 'Solana Network Hits New All-Time High in Daily Transactions',
    market: 'SOL/USD',
    direction: 'long',
    collateral: 5,
    leverage: 75,
    entryPrice: 95,
    exitPrice: 108,
    takeProfit: 100,
    stopLoss: null,
    pnl: 51.32,
    pnlPercent: 1026.3,
    openedAt: randomPastDate(72),
    closedAt: randomPastDate(36),
    status: 'closed',
  },
  {
    id: 'trade-closed-3',
    newsId: 'news-7',
    newsHeadline: 'Ethereum ETF Approval Expected Within Weeks',
    market: 'ETH/USD',
    direction: 'long',
    collateral: 10,
    leverage: 75,
    entryPrice: 2450,
    exitPrice: 2380,
    takeProfit: 100,
    stopLoss: null,
    pnl: -21.43,
    pnlPercent: -214.3,
    openedAt: randomPastDate(96),
    closedAt: randomPastDate(72),
    status: 'closed',
  },
  {
    id: 'trade-closed-4',
    newsId: 'news-9',
    newsHeadline: 'Gold Reaches New Record High Amid Economic Uncertainty',
    market: 'XAU/USD',
    direction: 'long',
    collateral: 1,
    leverage: 75,
    entryPrice: 2100,
    exitPrice: 2150,
    takeProfit: 100,
    stopLoss: null,
    pnl: 1.79,
    pnlPercent: 178.6,
    openedAt: randomPastDate(120),
    closedAt: randomPastDate(96),
    status: 'closed',
  },
  {
    id: 'trade-closed-5',
    newsId: 'news-11',
    newsHeadline: 'Dogecoin Rallies 20% on Elon Musk Twitter Activity',
    market: 'DOGE/USD',
    direction: 'short',
    collateral: 2,
    leverage: 75,
    entryPrice: 0.095,
    exitPrice: 0.088,
    takeProfit: 100,
    stopLoss: null,
    pnl: 11.05,
    pnlPercent: 552.6,
    openedAt: randomPastDate(144),
    closedAt: randomPastDate(120),
    status: 'closed',
  },
  {
    id: 'trade-closed-6',
    newsId: 'news-12',
    newsHeadline: 'Amazon Web Services Launches New AI Training Platform',
    market: 'AMZN/USD',
    direction: 'long',
    collateral: 5,
    leverage: 75,
    entryPrice: 178,
    exitPrice: 172,
    takeProfit: 100,
    stopLoss: null,
    pnl: -12.64,
    pnlPercent: -252.8,
    openedAt: randomPastDate(168),
    closedAt: randomPastDate(144),
    status: 'closed',
  },
  {
    id: 'trade-closed-7',
    newsId: 'news-17',
    newsHeadline: 'AMD Announces Next-Gen AI Accelerators to Compete with NVIDIA',
    market: 'AMD/USD',
    direction: 'long',
    collateral: 2,
    leverage: 75,
    entryPrice: 145,
    exitPrice: 162,
    takeProfit: 100,
    stopLoss: null,
    pnl: 17.59,
    pnlPercent: 879.3,
    openedAt: randomPastDate(192),
    closedAt: randomPastDate(168),
    status: 'closed',
  },
];

/**
 * Mock user profile data
 */
export const mockUserProfile = {
  id: 'user-mock-1',
  walletAddress: '0x1234567890abcdef1234567890abcdef12345678',
  email: 'trader@example.com',
  balance: 1000,
  createdAt: '2024-01-15T10:00:00Z',
};

/**
 * Calculate mock stats from trades
 */
export function calculateMockStats() {
  const allClosed = mockClosedTrades;
  const winningTrades = allClosed.filter((t) => t.pnl > 0);
  const totalPnL = allClosed.reduce((sum, t) => sum + t.pnl, 0);

  return {
    totalTrades: mockActiveTrades.length + allClosed.length,
    winRate: allClosed.length > 0 
      ? Math.round((winningTrades.length / allClosed.length) * 100 * 10) / 10 
      : 0,
    totalPnL: Math.round(totalPnL * 100) / 100,
    bestTrade: allClosed.reduce((best, t) => 
      t.pnl > (best?.pnl || -Infinity) ? t : best, null),
    worstTrade: allClosed.reduce((worst, t) => 
      t.pnl < (worst?.pnl || Infinity) ? t : worst, null),
  };
}

export default {
  mockNews,
  mockActiveTrades,
  mockClosedTrades,
  mockUserProfile,
  calculateMockStats,
};

